name: Build and Push Arch arm64 Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.arch-arm64
      - .github/workflows/arch-arm64-push.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.arch-arm64
          platforms: linux/arm64
          push: true
          tags: garo/openssh-client:arch-arm64
