name: Build and Push Debian Image

on:
  push:
    branches:
      - dev
    paths:
      - Dockerfile.debian
      - .github/workflows/debian-push.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: garo/openssh-client:debian
